services:
  web:
    image: ghcr.io/laboratoire-sion/laboratoiresion-v1:${BRANCH_NAME}
    container_name: laboratoiresion-v1-${BRANCH_NAME}
    restart: always
    ports:
      - "8001:3000" # Next.js exposed on 8001 internally
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
